#!/bin/bash

main() {
  examplesDir="examples"
  if [[ $# -gt 0 ]]; then
    examplesDir=$1
  fi
  echo "Running examples in $examplesDir"
  echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
  for example in $examplesDir/*.cl; do
    if [[ $example != *"~"* ]]; then
        echo Testing \'$example\'
        ./myparser $example >/dev/null 2>&1
        if [[ $? != 0 ]]; then
          errCode=$?
          echo Failed test \'$example\'
          exit $errCode
        fi
    fi
  done
  echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
  echo All tests succeeded! Well Done!
  echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"    
}

main $@
